#!/usr/bin/python3

import sys
import dropbox_sync.dropbox_syncer as dbx
import drive_sync.drive_syncer as drv
import gmail_sync.gmail_syncer as gml

verbose = len(sys.argv) == 2 and sys.argv[1].lower() == "--verbose"
sync_file_path = "/home/piyush/projects/File-Syncer/sync_files.txt"

# Dropbox
if verbose: print("DROPBOX")
try:
    dbx.sync(sync_file_path, "sync_files", verbose)
except Exception as e:
    print("Exception occurred in sync.py while syncing dropbox: \"{0}\"".format(str(e)))
if verbose: print()

# Google Drive
if verbose: print("DRIVE")
try:
    drv.sync(sync_file_path, "sync_files", verbose)
except Exception as e:
    print("Exception occurred in sync.py while syncing drive: \"{0}\"".format(str(e)))
if verbose: print()

# Gmail
if verbose: print("GMAIL")
try:
    gml.sync(sync_file_path, verbose)
except Exception as e:
    print("Exception occurred in sync.py while syncing gmail: \"%s\"" % str(e))
if verbose: print()

# Facebook
pass

